Added API discovery.
FINTLabs/fint-admin-portal-backend pull request #15
Opened 2020-05-29 08:27 UTC by asgeirn

Discovers main class endpoints from running controllers.

2020-06-11 19:58 UTC, asgeirn commented on src/main/java/no/fint/portal/admin/service/ApiDiscoveryService.java
> +                    .map(c -> new ComponentClass(StringUtils.substringAfterLast(c, "/"), c))
This might fail if the component path contains more slashes than expected - removing `componentPath` from the start is a safer option in my opinion.

2020-09-10 07:24 UTC, OlaStalberg approved these changes

2020-09-16 13:41 UTC, fsjovatsen requested changes

2020-09-16 13:41 UTC, fsjovatsen commented on src/main/java/no/fint/portal/admin/service/ApiDiscoveryService.java
> +    public List<ComponentClass> getClassesForComponent(String componentName, String componentPath) {
Should this method be called `getClassesFromComponent`

2020-09-17 07:13 UTC, asgeirn reviewed
Renamed method as requested.

2020-09-17 07:14 UTC, merged